name: Deploy Python Telegram Bot

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the environment (Ubuntu latest)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install python-telegram-bot  # Install the required dependencies

    - name: Make the binary executable (if present)
      run: chmod +x kalaji || echo "Binary not found, skipping."

    - name: Run the bot script
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        python kalaji.py  # Run your bot script

